# NumPy 

Este cuaderno contiene **15 ejemplos cortos e independientes** para introducir conceptos clave de NumPy.
Cada ejemplo incluye:
- una **explicación previa** (markdown), y
- código con **comentarios** donde sea útil.

Sugerencia de estudio: ejecuta un ejemplo, cambia un parámetro (tamaño, `axis`, condición, etc.) y vuelve a ejecutarlo.


In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)


## Ejemplo 1 — Crear arreglos e inspeccionar propiedades

**Objetivo:** crear arreglos (arrays) desde listas y entender sus propiedades básicas.

**Conceptos clave:**  
- `shape`: la forma (dimensiones) del arreglo  
- `dtype`: el tipo de dato almacenado  
- `ndim`: cuántas dimensiones tiene

**Qué observar:** cómo cambia `shape` y `ndim` entre un arreglo 1D y una matriz 2D.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [2]:
a = np.array([1, 2, 3, 4, 5])          # arreglo 1D
b = np.array([[1, 2, 3], [4, 5, 6]])     # matriz 2D

print("a:", a, "shape:", a.shape, "dtype:", a.dtype, "ndim:", a.ndim)
print("b:\n", b)
print("b shape:", b.shape, "dtype:", b.dtype, "ndim:", b.ndim)


a: [1 2 3 4 5] shape: (5,) dtype: int64 ndim: 1
b:
 [[1 2 3]
 [4 5 6]]
b shape: (2, 3) dtype: int64 ndim: 2


## Ejemplo 2 — Generación de datos: arange, linspace, zeros/ones/full

**Objetivo:** generar secuencias y arreglos inicializados sin usar bucles.

**Conceptos clave:**  
- `np.arange(inicio, fin, paso)` crea valores con paso fijo  
- `np.linspace(inicio, fin, n)` crea **n puntos** igualmente espaciados  
- `zeros`, `ones`, `full` crean arreglos base

**Qué observar:** diferencias entre “paso” vs “n puntos”.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [3]:
x = np.arange(0, 10, 2)        # 0,2,4,6,8
y = np.linspace(0, 1, 6)         # 6 puntos entre 0 y 1
z = np.zeros((2, 3))             # matriz 2x3 con ceros
o = np.ones((2, 3))              # matriz 2x3 con unos
f = np.full((2, 3), 7)           # matriz 2x3 rellena con 7

print("arange:", x)
print("linspace:", y)
print("zeros:\n", z)
print("ones:\n", o)
print("full:\n", f)


arange: [0 2 4 6 8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full:
 [[7 7 7]
 [7 7 7]]


## Ejemplo 3 — Indexación y slicing (1D y 2D)

**Objetivo:** acceder a elementos y sub-arreglos (rebanadas).

**Conceptos clave:**  
- Indexación: `m[fila, columna]`  
- Slicing: `:` para rangos  
- Submatrices: combinando slices

**Nota:** muchas rebanadas son **vistas** (views), no copias. Cambiar la vista puede cambiar el arreglo original.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [4]:
arr = np.arange(1, 13)                 # 1..12
m = arr.reshape(3, 4)                    # matriz 3x4 (3 filas, 4 columnas)

print("m:\n", m)
print("m[0, 0] =", m[0, 0])              # primer elemento
print("primera fila:", m[0, :])          # fila 0, todas las columnas
print("última columna:", m[:, -1])       # todas las filas, última columna
print("submatriz (filas 0..1, cols 1..2):\n", m[0:2, 1:3])


m:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m[0, 0] = 1
primera fila: [1 2 3 4]
última columna: [ 4  8 12]
submatriz (filas 0..1, cols 1..2):
 [[2 3]
 [6 7]]


## Ejemplo 4 — Máscaras booleanas (filtrado)

**Objetivo:** filtrar datos usando condiciones.

**Conceptos clave:**  
- Una máscara es un arreglo de `True/False`  
- `data[mask]` devuelve solo los elementos donde `mask` es `True`

**Qué observar:** cambia la condición (>=50, >70, etc.) y mira cómo cambia la salida.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [5]:
rng = np.random.default_rng(42)        # RNG reproducible
data = rng.integers(0, 100, size=12)     # enteros 0..99
mask = data >= 50                        # condición: valores >= 50

print("data:", data)
print("mask:", mask)
print("valores >= 50:", data[mask])


data: [ 8 77 65 43 43 85  8 69 20  9 52 97]
mask: [False  True  True False False  True False  True False False  True  True]
valores >= 50: [77 65 85 69 52 97]


## Ejemplo 5 — Fancy indexing (selección por índices)

**Objetivo:** seleccionar elementos con un arreglo de índices.

**Conceptos clave:**  
- Slicing toma rangos contiguos  
- Fancy indexing permite posiciones **específicas** (no contiguas)

**Qué observar:** cambia `idx` y selecciona otros elementos.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])
idx = np.array([0, 2, 5])     # posiciones específicas

print("arr:", arr)
print("idx:", idx)
print("arr[idx]:", arr[idx])


arr: [10 20 30 40 50 60]
idx: [0 2 5]
arr[idx]: [10 30 60]


## Ejemplo 6 — Broadcasting

**Objetivo:** entender cómo NumPy opera con arreglos de formas distintas.

**Conceptos clave:**  
- Broadcasting “expande” dimensiones compatibles sin bucles explícitos  
- Muy útil para sumar un vector a cada fila (o columna)

**Qué observar:** revisa `A.shape`, `v.shape`, `col.shape`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [7]:
A = np.arange(1, 7).reshape(2, 3)
v = np.array([10, 20, 30])          # shape (3,)

print("A:\n", A)
print("v:", v)
print("A + v (broadcast en filas):\n", A + v)

col = np.array([[100], [200]])      # shape (2,1)
print("col:\n", col)
print("A + col (broadcast en columnas):\n", A + col)


A:
 [[1 2 3]
 [4 5 6]]
v: [10 20 30]
A + v (broadcast en filas):
 [[11 22 33]
 [14 25 36]]
col:
 [[100]
 [200]]
A + col (broadcast en columnas):
 [[101 102 103]
 [204 205 206]]


## Ejemplo 7 — Funciones vectorizadas (ufuncs)

**Objetivo:** aplicar funciones matemáticas elemento a elemento.

**Conceptos clave:**  
- `np.sin`, `np.exp`, potencias, etc. funcionan sobre arreglos completos  
- Evita bucles Python y suele ser más rápido

**Qué observar:** salida de `sin` en diferentes puntos.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [8]:
x = np.linspace(0, 2*np.pi, 6)
print("x:", x)
print("sin(x):", np.sin(x))
print("exp(x):", np.exp(x))
print("x^2:", x**2)


x: [0.    1.257 2.513 3.77  5.027 6.283]
sin(x): [ 0.     0.951  0.588 -0.588 -0.951 -0.   ]
exp(x): [  1.      3.514  12.345  43.376 152.406 535.492]
x^2: [ 0.     1.579  6.317 14.212 25.266 39.478]


## Ejemplo 8 — Agregaciones y axis

**Objetivo:** resumir datos y entender `axis`.

**Conceptos clave:**  
- Sin `axis`: agrega todo  
- `axis=0`: por columnas  
- `axis=1`: por filas

**Qué observar:** compara `sum(axis=0)` vs `sum(axis=1)`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [9]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("m:\n", m)
print("suma total:", m.sum())
print("suma por columna (axis=0):", m.sum(axis=0))
print("suma por fila (axis=1):", m.sum(axis=1))
print("media por columna:", m.mean(axis=0))
print("máximo por fila:", m.max(axis=1))


m:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
suma total: 45
suma por columna (axis=0): [12 15 18]
suma por fila (axis=1): [ 6 15 24]
media por columna: [4. 5. 6.]
máximo por fila: [3 6 9]


## Ejemplo 9 — Ordenar y argsort

**Objetivo:** ordenar valores y recuperar el orden de índices.

**Conceptos clave:**  
- `np.sort` devuelve valores ordenados  
- `np.argsort` devuelve índices que ordenarían el arreglo

**Qué observar:** `a[argsort(a)]` coincide con `sort(a)`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [10]:
rng = np.random.default_rng(7)
a = rng.integers(0, 100, size=10)

print("a:", a)
sorted_a = np.sort(a)
order = np.argsort(a)

print("ordenado:", sorted_a)
print("argsort índices:", order)
print("a[order]:", a[order])


a: [94 62 68 89 57 77 83 22  5 30]
ordenado: [ 5 22 30 57 62 68 77 83 89 94]
argsort índices: [8 7 9 4 1 2 5 6 3 0]
a[order]: [ 5 22 30 57 62 68 77 83 89 94]


## Ejemplo 10 — reshape, transpuesta, flatten vs ravel

**Objetivo:** cambiar la forma y “aplanar” arreglos.

**Conceptos clave:**  
- `reshape` cambia la forma (a veces devuelve vista)  
- `.T` transpone (para 2D intercambia filas/columnas)  
- `flatten` suele crear copia  
- `ravel` intenta devolver una vista

**Qué observar:** modifica `m` y ve si afecta `ravel` en algunos casos.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [11]:
m = np.arange(1, 13).reshape(3, 4)
print("m:\n", m)
print("transpuesta:\n", m.T)

flat_copy = m.flatten()   # copia
flat_view = m.ravel()     # vista (si es posible)
print("flatten (copia):", flat_copy)
print("ravel (vista-ish):", flat_view)

m2 = m.reshape(2, 6)
print("reshape a 2x6:\n", m2)


m:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transpuesta:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
flatten (copia): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel (vista-ish): [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape a 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Ejemplo 11 — Stacking y splitting

**Objetivo:** combinar y dividir arreglos.

**Conceptos clave:**  
- `hstack` (horizontal), `vstack` (vertical)  
- `concatenate` generaliza con `axis`  
- `split` divide por cortes

**Qué observar:** diferencia entre `axis=0` vs `axis=1` en `concatenate`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("hstack:", np.hstack([a, b]))

A = np.arange(1, 7).reshape(2, 3)
B = np.arange(7, 13).reshape(2, 3)

print("A:\n", A)
print("B:\n", B)
print("vstack:\n", np.vstack([A, B]))
print("concatenate axis=1 (lado a lado):\n", np.concatenate([A, B], axis=1))

parts = np.split(np.arange(10), [3, 7])  # cortes en 3 y 7
print("split en [0..2], [3..6], [7..9]:", parts)


hstack: [1 2 3 4 5 6]
A:
 [[1 2 3]
 [4 5 6]]
B:
 [[ 7  8  9]
 [10 11 12]]
vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
concatenate axis=1 (lado a lado):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
split en [0..2], [3..6], [7..9]: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


## Ejemplo 12 — Números aleatorios reproducibles

**Objetivo:** generar datos aleatorios de manera reproducible.

**Conceptos clave:**  
- `default_rng(seed)` define una semilla  
- uniformes, normales, enteros

**Qué observar:** cambia la semilla y compara resultados.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [13]:
rng = np.random.default_rng(123)
u = rng.random(5)                   # uniforme [0,1)
n = rng.normal(0, 1, size=5)        # normal
ints = rng.integers(1, 7, size=10)  # dado 1..6

print("uniforme:", u)
print("normal:", n)
print("tiradas de dado:", ints)


uniforme: [0.682 0.054 0.22  0.184 0.176]
normal: [ 0.577 -0.636  0.542 -0.317 -0.322]
tiradas de dado: [1 4 2 2 2 5 5 2 3 5]


## Ejemplo 13 — Álgebra lineal: dot, @, solve

**Objetivo:** introducir operaciones comunes de álgebra lineal.

**Conceptos clave:**  
- `dot` (producto punto)  
- `@` (multiplicación matricial)  
- `np.linalg.solve` resuelve `A x = b`

**Qué observar:** verifica `A @ x` y compáralo con `b`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [14]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
print("dot(v, w) =", np.dot(v, w))   # producto punto

A = np.array([[3, 1],
              [1, 2]], dtype=float)
b = np.array([9, 8], dtype=float)

x = np.linalg.solve(A, b)           # resuelve A x = b
print("A:\n", A)
print("b:", b)
print("solución x:", x)
print("verificación A@x:", A @ x)


dot(v, w) = 32
A:
 [[3. 1.]
 [1. 2.]]
b: [9. 8.]
solución x: [2. 3.]
verificación A@x: [9. 8.]


## Ejemplo 14 — NaN y funciones nan*

**Objetivo:** manejar valores faltantes representados como `NaN`.

**Conceptos clave:**  
- `mean()` devuelve `NaN` si hay `NaN`  
- `np.nanmean` ignora `NaN`

**Qué observar:** compara `mean` vs `nanmean`.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [15]:
data = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
print("data:", data)
print("mean (da NaN):", data.mean())
print("nanmean (ignora NaN):", np.nanmean(data))
print("nanmax:", np.nanmax(data))


data: [ 1.  2. nan  4. nan  6.]
mean (da NaN): nan
nanmean (ignora NaN): 3.25
nanmax: 6.0


## Ejemplo 15 — Guardar y cargar: npy y npz

**Objetivo:** persistir arreglos en disco.

**Conceptos clave:**  
- `np.save` / `np.load` para un arreglo (`.npy`)  
- `np.savez` para varios arreglos (`.npz`)

**Qué observar:** archivos creados en el directorio actual del notebook.

**Qué deberías observar al ejecutar:**
- La salida.
- Cómo cambia al modificar parámetros.


In [16]:
arr = np.arange(10)**2
np.save("cuadrados.npy", arr)         # guarda 1 arreglo

loaded = np.load("cuadrados.npy")
print("cargado:", loaded)

a = np.arange(5)
b = np.arange(5, 10)
np.savez("dos_arreglos.npz", a=a, b=b)  # guarda varios arreglos con nombres

z = np.load("dos_arreglos.npz")
print("archivos en npz:", z.files)
print("a:", z["a"])
print("b:", z["b"])


cargado: [ 0  1  4  9 16 25 36 49 64 81]
archivos en npz: ['a', 'b']
a: [0 1 2 3 4]
b: [5 6 7 8 9]
